include: package:surf_lint_rules/analysis_options.yaml
# include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  rules:
    # turn on after refactor
    - prefer-match-file-name: false
        # exclude:
        #   - test/**
    - format-comment: false
    - avoid-returning-widgets: false
    - prefer-moving-to-variable: false
    - avoid-passing-async-when-sync-expected: false
  rules-exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/generated_plugin_registrant.dart'
    - 'components/atol_flutter/**'
    -  build/**
    -  lib/generated

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/generated_plugin_registrant.dart'
    -  build/**
    -  lib/generated
  errors:
    invalid_annotation_target: ignore
    implementation_imports: ignore

linter:
  rules:
    avoid_redundant_argument_values: true
    # avoid_dynamic: true
    avoid_relative_lib_imports: true
    # prefer_relative_imports: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    directives_ordering: true
    omit_local_variable_types: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_in_for_each: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    require_trailing_commas: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    avoid_annotating_with_dynamic: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    comment_references: false
